/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion;
import concesionarioCoches.ColorNoValidoException;
import concesionarioCoches.Ficheros;
import concesionarioCoches.Gestion;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import concesionarioCoches.Concesionario;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jaime
 */
public class Principal extends javax.swing.JFrame {
    private File archivo= new File("Sin_titulo.objs");
    private File ficheroCreado = null;
    /**
     * Creates new form TestConcesionarioGrafico
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nuevo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        guardado = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        numero = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        numero1 = new javax.swing.JMenuItem();
        numero2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem5.setText("jMenuItem5");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SinTitulo.obj");
        setFocusCycleRoot(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("Archivo");

        nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jMenu1.add(nuevo);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Guardar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        guardado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        guardado.setText("GuardarComo");
        guardado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardadoActionPerformed(evt);
            }
        });
        jMenu1.add(guardado);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Abrir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("GestionarCoche");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("CrearCoche");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("EliminarCoche");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);
        jMenu2.add(jSeparator2);

        jMenu7.setText("Buscar");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("MostrarConcesionario");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("MostrarCocheColor");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("MostrarCocheMatricula");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        numero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        numero.setText("Mostrar Numero De Coches");
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });
        jMenu7.add(numero);

        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        jMenu8.setText("Ayuda");

        numero1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        numero1.setText("Ver ayuda");
        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });
        jMenu8.add(numero1);

        numero2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        numero2.setText("Acerca de ...");
        numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero2ActionPerformed(evt);
            }
        });
        jMenu8.add(numero2);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        metodoGuardar();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void metodoGuardar() throws HeadlessException {
        if(ficheroCreado == archivo){
            try {
                Ficheros.guardar(Gestion.getConcesionario(), archivo);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "guardado");
            }
        }else{
            JFileChooser guardarComo = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("archivo.obj", "OBJ");
            guardarComo.setFileFilter(filtro);
            
            if(JFileChooser.APPROVE_OPTION == guardarComo.showSaveDialog(guardado)){
                archivo = guardarComo.getSelectedFile();
                if(archivo.exists()){
                    int num = JOptionPane.showConfirmDialog(guardarComo, "¿Desea sobreescrbir?", "confirmar", JOptionPane.YES_NO_CANCEL_OPTION);
                    
                    if(num ==  0 ){
                        
                        try {
                            Ficheros.guardar(Gestion.getConcesionario(), archivo);
                            this.setTitle(archivo.getName());
                           
                            
                        } catch (IOException ex) {
                            JOptionPane.showMessageDialog(this, "guardado");
                        }
                    }else if(num == 1){
                        this.setVisible(false);
                    }
                }else{
                    try {
                        Ficheros.guardar(Gestion.getConcesionario(), archivo);
                        
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "guardado");
                    }
                }
                
            }
        }
    }

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       
           new AltaCoche(this).setVisible(true);
      
      
           
        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       if(Gestion.concesionario.size()==0){
        JOptionPane.showMessageDialog(this, "Aun no hay coches en el concesionario");
    }else{
         new MostrarCoches(this, rootPaneCheckingEnabled).setVisible(true);
    }
            
      
                  
        
        //     Logger.getLogger(AltaCoche.class.getName()).log(Level.SEVERE, null, ex)
              //JOptionPane.showMessageDialog(this, ex.getMessage(),"Error en el color", JOptionPane.ERROR_MESSAGE);
          
            
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        if(Gestion.concesionario.size()==0){
        JOptionPane.showMessageDialog(this, "Aun no hay coches en el concesionario!");
    }else{
        new MostrarPorColor(this, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if(Gestion.concesionario.size()==0){
        JOptionPane.showMessageDialog(this, "Aun no hay coches en el concesionario");
    }else{
        new MostrarPorMatricula(this, rootPaneCheckingEnabled).setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        
          JOptionPane.showMessageDialog(this, "El numero de coches es: " + Gestion.concesionario.size());
    }//GEN-LAST:event_numeroActionPerformed

    private void guardadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardadoActionPerformed
      JFileChooser guardarComo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("archivo.obj", "OBJ");
        guardarComo.setFileFilter(filtro);
        
        if(JFileChooser.APPROVE_OPTION == guardarComo.showSaveDialog(jMenuItem8)){
            archivo = guardarComo.getSelectedFile();
            ficheroCreado = archivo;
            if(archivo.exists()){
                
                int num = JOptionPane.showConfirmDialog(guardarComo, "¿sobreescrbir?", "confirmar", JOptionPane.YES_NO_CANCEL_OPTION);
                if(num == 0){
                    
                    
                    try {
                        Ficheros.guardarComo(Gestion.getConcesionario(), archivo);
                        this.setTitle(archivo.getName());
                       // JOptionPane.showConfirmDialog(guardarComo, "guardado");
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "guardado");
                    }
                }else if (num == 1){
                    guardarComo.setVisible(false);
                }
            }else{
                try {
                     Ficheros.guardarComo(Gestion.getConcesionario(), archivo);
                    
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "guardado");
                }
            }
        }
         
    }//GEN-LAST:event_guardadoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       JFileChooser abrir = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("archivo.obj", "OBJ");
        abrir.setFileFilter(filtro);
        if(JFileChooser.APPROVE_OPTION == abrir.showOpenDialog(jMenuItem3)){
            archivo = abrir.getSelectedFile();
            ficheroCreado = archivo;
            this.setTitle(archivo.getName());
            try {
               Gestion.concesionario = Ficheros.abrir(archivo);
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
    if(Gestion.concesionario.size()==0){
        JOptionPane.showMessageDialog(this, "Aun no hay coches en el concesionario");
    }else{
         new EliminarCoche(this, rootPaneCheckingEnabled).setVisible(true);
    }
       
    // new BajaCoche(this).setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed
         new AyudaFrame().setVisible(true);
    }//GEN-LAST:event_numero1ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
         
        salir();
    }//GEN-LAST:event_salirActionPerformed

    private void salir() throws HeadlessException {
        int num = JOptionPane.showConfirmDialog(salir, "¿Desea guardar los cambios?", "CONFIRMACION", JOptionPane.YES_NO_CANCEL_OPTION);
        if(num == 0){
            metodoGuardar();
            System.exit(0);
        }else if (num==1){
            System.exit(0);
        }else
            this.setVisible(true);
        
        
        
// System.exit(0);
    }

    private void numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero2ActionPerformed
       
         new AcercaDe().setVisible(true);
    }//GEN-LAST:event_numero2ActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        if(Gestion.mostrarNCoches()> 0){
           int num = JOptionPane.showConfirmDialog(nuevo, "¿desea guardar los cambios?", "CONFIRMACION", JOptionPane.YES_NO_CANCEL_OPTION);
            
            if(num == 0){
                 metodoGuardar();
                            
                
                archivo = new File("nuevo");
                Gestion.getConcesionario().vaciar();
                
            }else if (num == 1){
                archivo = new File("nuevo.obj");
                Gestion.getConcesionario().vaciar();
                this.setTitle(archivo.getName());
            }
      
            
        }else{
            archivo = new File("nuevo.obj");
            Gestion.getConcesionario().vaciar();
            this.setTitle(archivo.getName());
        }
    }//GEN-LAST:event_nuevoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        salir();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
               Principal concesionario = new Principal();
               concesionario.setLocationRelativeTo(null);
                concesionario.setVisible(true);
                           }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem guardado;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem nuevo;
    private javax.swing.JMenuItem numero;
    private javax.swing.JMenuItem numero1;
    private javax.swing.JMenuItem numero2;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables


}
